version: '3.1'

services:

        database:
                container_name: database
                image: postgres:latest
                restart: always
                environment:
                  POSTGRES_DB: dkdwproject
                  POSTGRES_USER: admin
                  POSTGRES_PASSWORD: pass123
                ports:
                - "6432:5432"

        frontend:
                container_name: frontend
                depends_on:
                        - backend
                        - database
                image: frontend
                build:
                        context: ./frontend
                        dockerfile: Dockerfile
                ports:
                        - "80:80"

        backend:
                container_name: backend
                image: backend
                build:
                        context: ./backend
                        dockerfile: docker/Dockerfile
                ports:
                        - "8081:8080"