version:  '3.1'

services:
  db:
    container_name: dkdwprojectDb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dkdwproject
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"