on:
  push:
    branches:
      - master
name: Deploy to Heroku

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dkdw-project"
          heroku_email: "notedeagle@gmail.com"
          usedocker: true