name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: 'docker-compose.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"postgres","appname":"database","apptype":"web"},{"imagename":"backend","appname":"backend","apptype":"web"},{"imagename":"frontend","appname":"frontend","apptype":"web"}]' 
